version: '2'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - 80:80
      - 443:443
  fpm:
    build: docker/php-fpm
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: homestead
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306